# Generated by Django 4.2.7 on 2023-11-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('naver_card_id', models.TextField()),
                ('annual_fee', models.TextField()),
                ('base_performance', models.TextField()),
                ('fuel', models.TextField(blank=True, null=True)),
                ('shoping', models.TextField(blank=True, null=True)),
                ('supermarket', models.TextField(blank=True, null=True)),
                ('convenience_store', models.TextField(blank=True, null=True)),
                ('eat_out', models.TextField(blank=True, null=True)),
                ('cafe_bakery', models.TextField(blank=True, null=True)),
                ('movie', models.TextField(blank=True, null=True)),
                ('public_transport', models.TextField(blank=True, null=True)),
                ('maintenance', models.TextField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('parenting', models.TextField(blank=True, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('leisure', models.TextField(blank=True, null=True)),
                ('airline_mileage', models.TextField(blank=True, null=True)),
                ('premium', models.TextField(blank=True, null=True)),
                ('hi_pass', models.TextField(blank=True, null=True)),
                ('auto', models.TextField(blank=True, null=True)),
                ('medical', models.TextField(blank=True, null=True)),
                ('beauty', models.TextField(blank=True, null=True)),
                ('points_cashback', models.TextField(blank=True, null=True)),
                ('easy_payment', models.TextField(blank=True, null=True)),
                ('rental', models.TextField(blank=True, null=True)),
                ('pet', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('dcls_month', models.TextField()),
                ('join_deny', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('max_limit', models.FloatField(blank=True, null=True)),
                ('etc_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('operation_scale', models.FloatField()),
                ('set_date', models.TextField()),
                ('total_reward', models.FloatField(blank=True, null=True)),
                ('revenue_3m', models.FloatField(blank=True, null=True)),
                ('revenue_6m', models.FloatField(blank=True, null=True)),
                ('revenue_1y', models.FloatField(blank=True, null=True)),
                ('revenue_3y', models.FloatField(blank=True, null=True)),
                ('risk_level', models.IntegerField()),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('dcls_month', models.TextField()),
                ('join_deny', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('max_limit', models.FloatField(blank=True, null=True)),
                ('etc_note', models.TextField()),
                ('mtrt_int', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('save_trm', models.TextField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('intr_rate_type_nm', models.TextField()),
                ('rsrv_type_nm', models.TextField()),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.saving')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('save_trm', models.TextField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('intr_rate_type_nm', models.TextField()),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.deposit')),
            ],
        ),
    ]
