# Generated by Django 4.2.7 on 2023-11-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=10)),
                ('join_deny', models.IntegerField()),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField()),
                ('max_limit', models.FloatField()),
                ('etc_note', models.TextField()),
            ],
        ),
    ]
