# Generated by Django 4.2.7 on 2023-11-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("operation_scale", models.FloatField()),
                ("set_date", models.TextField()),
                ("total_reward", models.FloatField()),
                ("revenue_3m", models.FloatField()),
                ("revenue_6m", models.FloatField()),
                ("revenue_1y", models.FloatField()),
                ("revenue_3y", models.FloatField()),
                ("risk_level", models.IntegerField()),
                ("keyword", models.TextField()),
            ],
        ),
    ]
