# Generated by Django 4.2.7 on 2023-11-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_fund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="keyword",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="revenue_1y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="revenue_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="revenue_3y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="revenue_6m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fund",
            name="total_reward",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
