# Generated by Django 4.2.7 on 2023-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('ttb', models.TextField()),
                ('tts', models.TextField()),
                ('deal_bas_r', models.TextField()),
                ('bkpr', models.TextField()),
                ('yy_efee_r', models.TextField()),
                ('ten_dd_efee_r', models.TextField()),
                ('kftc_bkpr', models.TextField()),
                ('kftc_deal_bas_r', models.TextField()),
                ('cur_nm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('naver_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('video_id', models.TextField()),
            ],
        ),
    ]
