# Generated by Django 4.2.7 on 2023-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('now_price', models.TextField()),
                ('price_raise', models.TextField()),
                ('price_raise_percent', models.TextField()),
                ('chart_url', models.TextField()),
                ('updated_day', models.TextField()),
                ('sichong', models.TextField()),
                ('trading_volume', models.TextField()),
            ],
        ),
    ]
