# Generated by Django 4.2.7 on 2023-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='chart_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sichong',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trading_volume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
