# Generated by Django 4.2.7 on 2023-11-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_stock_chart_url_alter_stock_sichong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('now_price', models.TextField()),
                ('price_raise', models.TextField()),
                ('price_raise_percent', models.TextField()),
                ('chart_url', models.TextField(blank=True, null=True)),
                ('updated_day', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='chart_url',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_day',
        ),
    ]
