# Generated by Django 4.2.7 on 2023-11-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_index_remove_stock_chart_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_raise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
